import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#FAFAF2' },
  scroll: { flex: 1 },
  content: { paddingBottom: 12 },
  body: { paddingHorizontal: 12, gap: 14 },
  hero: { backgroundColor: '#EAF3E4', overflow: 'hidden', paddingHorizontal: 16, paddingBottom: 10 },
  heroWash: { ...StyleSheet.absoluteFill, backgroundColor: 'rgba(255,255,248,0.22)' },
  bellMask: { position: 'absolute', top: 5, right: 5, width: 10, height: 10, borderRadius: 5, backgroundColor: '#FFFFFF' },
  top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', height: 54 },
  logo: { width: 165, height: 55 },
  bell: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  dot: { position: 'absolute', top: 2, right: 2, width: 8, height: 8, borderRadius: 4, backgroundColor: '#ED493F' },
  heroRow: { flexDirection: 'row', minHeight: 120 },
  greetingBlock: { width: '55%', justifyContent: 'center', paddingVertical: 6 },
  greeting: { color: '#315162', fontSize: 16 },
  name: { color: '#125B35', fontWeight: '800', fontSize: 28, marginTop: 2 },
  subtitle: { color: '#315162', fontSize: 12, marginTop: 3 },
  location: { color: '#193C4A', fontSize: 11, fontWeight: '600', marginTop: 9, backgroundColor: '#F3F9EDEB', padding: 7, borderRadius: 16 },
  artwork: { width: '45%', flexDirection: 'row', alignItems: 'flex-end' },
  farmer: { position: 'absolute', right: 26, bottom: -8 },
  callout: { position: 'absolute', right: -12, top: 8 },
  card: { padding: 12, borderRadius: 18, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#EFF2E6' },
  heading: { flexDirection: 'row', alignItems: 'center', gap: 6, minHeight: 30, marginBottom: 10 },
  title: { flex: 1, color: '#123B4C', fontSize: 16, fontWeight: '800' },
  link: { minHeight: 32, justifyContent: 'center' },
  linkText: { color: '#234B50', fontSize: 11, lineHeight: 13, fontWeight: '600' },
  row: { flexDirection: 'row', gap: 8 },
  stat: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 3, minHeight: 72, borderRightWidth: 1, borderRightColor: '#E7EFE3', paddingRight: 4 },
  statLabel: { color: '#315162', fontSize: 10, lineHeight: 12 },
  statCopy: { flex: 1, minWidth: 0, gap: 3 },
  statIcon: { width: 24, height: 30, justifyContent: 'center', alignItems: 'center', borderRadius: 15, backgroundColor: '#E9F7E4' },
  value: { color: '#123B4C', fontSize: 24, fontWeight: '800' },
  unit: { color: '#244654', fontSize: 11, lineHeight: 13, fontWeight: '600' },
  meta: { color: '#315162', fontSize: 11, lineHeight: 14 },
  manage: { width: '23%', backgroundColor: '#EEF8EC', borderRadius: 12, justifyContent: 'center', alignItems: 'center', padding: 7, minHeight: 72 },
  manageText: { color: '#15422C', fontSize: 11, fontWeight: '700', textAlign: 'center' },
  arrow: { color: '#176D31', fontSize: 22, lineHeight: 23, fontWeight: '700' },
  opportunity: { borderColor: '#DBEAD6' },
  opportunityHeading: { flexDirection: 'row', alignItems: 'center', gap: 5, flexWrap: 'wrap', marginBottom: 8 },
  opportunityTitleGroup: { flexDirection: 'row', alignItems: 'center', gap: 5, flexGrow: 1, flexShrink: 1, flexBasis: '75%' },
  opportunityBody: { flexDirection: 'row', gap: 6, minHeight: 112 },
  opportunityArtwork: { flex: 28, minWidth: 0, justifyContent: 'center' },
  opportunityImage: { borderRadius: 10, backgroundColor: '#F0F5E8' },
  details: { flex: 42, minWidth: 0, gap: 4, justifyContent: 'center' },
  cropTitle: { color: '#123B4C', fontSize: 18, fontWeight: '700' },
  badge: { alignSelf: 'flex-start', backgroundColor: '#FFEEE9', color: '#BD3628', borderRadius: 10, paddingHorizontal: 6, paddingVertical: 2, fontSize: 10, fontWeight: '700' },
  offerPrice: { color: '#123B4C', fontSize: 20, fontWeight: '800' },
  offerUnit: { color: '#244654', fontSize: 11, fontWeight: '600' },
  marketReference: { color: '#667B80', fontSize: 10, lineHeight: 13 },
  aside: { flex: 30, minWidth: 0, justifyContent: 'space-between', gap: 6 },
  advantage: { backgroundColor: '#EFF9EF', borderRadius: 12, padding: 5, flex: 1, flexDirection: 'row', alignItems: 'center', gap: 4 },
  advantageTrend: { color: '#176D31', fontSize: 24, fontWeight: '700' },
  advantageCopy: { flex: 1, minWidth: 0, gap: 2 },
  advantageLabel: { color: '#315162', fontSize: 9 },
  advantageValue: { color: '#123B4C', fontSize: 13, fontWeight: '800' },
  opportunityEmpty: { paddingVertical: 16, gap: 10, alignItems: 'flex-start' },
  offers: { backgroundColor: '#12642D', minHeight: 44, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  offersText: { color: '#FFFFFF', fontSize: 11, fontWeight: '700' },
  marketTile: { flex: 1, minWidth: 0, backgroundColor: '#FCFCF8', borderRadius: 12, padding: 6, minHeight: 82, flexDirection: 'row', alignItems: 'center', gap: 3 },
  cropImage: { width: 42, height: 56 },
  marketCopy: { flex: 1, minWidth: 0 },
  cropName: { color: '#123B4C', fontSize: 11, lineHeight: 13, fontWeight: '600' },
  price: { color: '#123B4C', fontSize: 17, fontWeight: '800' },
  trend: { color: '#176D31', fontSize: 11, fontWeight: '700', marginTop: 3 },
  tile: { flex: 1, minWidth: 0, borderRadius: 12, padding: 9, gap: 7, minHeight: 92, justifyContent: 'center' },
  activityIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#FFFFFF80', alignItems: 'center', justifyContent: 'center' },
  activityTop: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  activityValue: { flex: 1, color: '#123B4C', fontSize: 20, fontWeight: '800' },
  activityAction: { color: '#15422C', fontSize: 11, fontWeight: '700', marginTop: 5 },
  quick: { alignItems: 'center', justifyContent: 'center', minHeight: 84 },
  quickLabel: { color: '#123B4C', fontSize: 11, fontWeight: '700', textAlign: 'center' },
  green: { backgroundColor: '#EFF9EF' },
  orange: { backgroundColor: '#FFF5E8' },
  blue: { backgroundColor: '#EEF5FF' },
  purple: { backgroundColor: '#F3EEFF' },
  nav: { backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E5EADF', paddingTop: 5, flexDirection: 'row' },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', height: 61, gap: 2 },
  navIcon: { width: 48, height: 33, alignItems: 'center', justifyContent: 'center', borderRadius: 20 },
  selected: { backgroundColor: '#EAF8E8' },
  navLabel: { color: '#686E69', fontSize: 11 },
  selectedLabel: { color: '#125B35', fontWeight: '800' },
  pressed: { opacity: 0.7 },
});



