export const dashboardAssets = {
  logo: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_logo.png'),
  hero: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_hero.png'),
  heroBackground: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_hero_background.png'),
  heroCallout: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/optimized/farmer_dashboard_hero_callout_trimmed.png'),
  tomato: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_tomato.png'),
  onion: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_onion.png'),
  potato: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_potato.png'),
  farm: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_farm_icon.png'),
  opportunity: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_opportunity_icon.png'),
  market: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_market_icon.png'),
  listing: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_listing_icon.png'),
  offer: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_offer_icon.png'),
  rupee: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_rupee_icon.png'),
  plus: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_quick_action_plus.png'),
  buyers: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_quick_action_buyers.png'),
  orders: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_quick_action_orders.png'),
  notification: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_notification_icon.png'),
  navHome: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_nav_home.png'),
  navMyFarm: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_nav_myfarm.png'),
  navSell: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_nav_sell.png'),
  navInsights: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_nav_insights.png'),
  navProfile: require('../../../assets/FarmPrism_Farmer_Dashboard_Assets/farmer_dashboard_nav_profile.png'),
};

