import { useRef, type PropsWithChildren } from 'react';
import { ActivityIndicator, Alert, Image, ImageBackground, Pressable, ScrollView, StyleSheet, Text, View, type ImageSourcePropType } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { FarmerStackParamList } from '../navigation/FarmerNavigator';
import { dashboardAssets as a } from '../components/farmer-dashboard/dashboardAssets';
import { s as navStyles } from '../components/farmer-dashboard/dashboardStyles';
import { useFarmerHomeAction } from '../hooks/useFarmerHomeAction';
import { myFarmIntentMessage, quintals, type FarmerMyFarmData, type MyFarmIntent } from '../components/farmer-my-farm/myFarmData';
import { useFarmerMyFarm } from '../hooks/useFarmerMyFarm';

function Icon({ source, size = 24 }: { source: ImageSourcePropType; size?: number }) { return <Image source={source} resizeMode="contain" style={{ width: size, height: size }} />; }
function Intent({ intent, label, children, style }: PropsWithChildren<{ intent: MyFarmIntent; label: string; style?: import('react-native').StyleProp<import('react-native').ViewStyle> }>) {
  return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={() => Alert.alert('Coming Soon', myFarmIntentMessage(intent))} style={({ pressed }) => [style, pressed && { opacity: 0.65 }]}>{children}</Pressable>;
}
function Heading({ title, icon = a.farm, action }: { title: string; icon?: number; action?: { label: string; intent: MyFarmIntent } }) {
  return <View style={s.heading}><Icon source={icon} /><Text style={s.headingText}>{title}</Text>{action && <Intent intent={action.intent} label={action.label} style={s.link}><Text style={s.linkText}>{action.label} ›</Text></Intent>}</View>;
}
function FarmerBottomNav({ onHome }: { onHome: () => void }) {
  const insets = useSafeAreaInsets();
  const open = useFarmerHomeAction();
  return <View style={[navStyles.nav, { paddingBottom: Math.max(insets.bottom, 18) }]}>{[{ label: 'Home', icon: a.navHome }, { label: 'My Farm', icon: a.navMyFarm }, { label: 'Sell', icon: a.navSell }, { label: 'Insights', icon: a.navInsights }, { label: 'Profile', icon: a.navProfile }].map(tab => <Pressable key={tab.label} accessibilityRole="tab" accessibilityLabel={tab.label} accessibilityState={{ selected: tab.label === 'My Farm' }} onPress={() => { if (tab.label === 'My Farm') return; if (tab.label === 'Home') onHome(); else if (tab.label === 'Profile') open('Farmer Profile'); else if (tab.label === 'Sell' || tab.label === 'Insights') open(tab.label); }} style={navStyles.navItem}><View style={[navStyles.navIcon, tab.label === 'My Farm' && navStyles.selected]}><Image source={tab.icon} resizeMode="contain" style={{ width: 28, height: 28, opacity: tab.label === 'My Farm' ? 1 : 0.65, ...(tab.label === 'My Farm' ? { tintColor: '#12642D' } : {}) }} /></View><Text style={[navStyles.navLabel, tab.label === 'My Farm' && navStyles.selectedLabel]}>{tab.label}</Text></Pressable>)}</View>;
}
function FarmerMyFarmState({ loading, error, onRetry, onHome }: { loading: boolean; error?: string; onRetry: () => void; onHome: () => void }) {
  return <View style={s.root}><StatusBar hidden /><View style={s.state}><Text style={s.stateTitle}>My Farm</Text>{loading ? <ActivityIndicator accessibilityLabel="Loading My Farm" size="large" color="#12642D" /> : <><Text accessibilityRole="alert" style={s.stateMessage}>{error ?? "We couldn't load your farm details."}</Text><Pressable accessibilityRole="button" accessibilityLabel="Try Again" onPress={onRetry} style={s.retry}><Text style={s.retryText}>Try Again</Text></Pressable></>}</View><FarmerBottomNav onHome={onHome} /></View>;
}
export function FarmerMyFarmScreen({ navigation }: NativeStackScreenProps<FarmerStackParamList, 'MyFarm'>) {
  const { data, loading, error, refresh } = useFarmerMyFarm();
  const onHome = () => navigation.popTo('Dashboard');
  if (loading || !data) return <FarmerMyFarmState loading={loading} error={error ?? undefined} onRetry={() => void refresh()} onHome={onHome} />;
  return <FarmerMyFarmView data={data} onHome={onHome} />;
}
// Presentational boundary accepts populated or empty data without touching Auth or services.
export function FarmerMyFarmView({ data, onHome }: { data: FarmerMyFarmData; onHome: () => void }) {
  const insets = useSafeAreaInsets();
  const scroll = useRef<ScrollView>(null);
  const open = useFarmerHomeAction();
  return <View style={s.root}><StatusBar hidden /><ScrollView ref={scroll} style={s.scroll} contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <ImageBackground source={a.heroBackground} resizeMode="cover" style={[s.hero, { paddingTop: Math.max(insets.top, 8) }]}>
      <View style={s.brandRow}><Image source={a.logo} resizeMode="contain" style={s.logo} /><Pressable accessibilityRole="button" accessibilityLabel="Notifications" onPress={() => open('Notifications')} style={s.bell}><Icon source={a.notification} /><View style={s.bellMask} /></Pressable></View>
      <View style={s.heroRow}><View style={s.intro}><Text style={s.title}>My Farm</Text><Text style={s.subtitle}>Manage your land, crops and produce in one place.</Text><Text style={s.location}>⌖ {data.farm.location || 'Add your farm location'}</Text></View><Image source={a.hero} resizeMode="contain" style={s.farmer} /><View style={s.heroAside}><Text style={s.callout}>Healthy Farms{'\n'}Prosperous Futures</Text><Intent intent={{ type: 'EDIT_FARM' }} label="Edit Farm" style={s.edit}><Text style={s.linkText}>✎ Edit Farm</Text></Intent></View></View>
    </ImageBackground>
    <View style={s.body}>
      <View style={s.card}><Heading title="Farm Overview" /><Intent intent={{ type: 'FARM_OVERVIEW' }} label="Farm Overview" style={s.overview}>
        {[{ value: data.farm.area?.toFixed(1) ?? '—', label: 'Acres', detail: 'Total Land', icon: a.listing }, { value: String(data.summary.cropCount), label: 'Crops', detail: 'You Grow', icon: a.farm }, { value: (data.summary.totalAvailableKg / 100).toLocaleString('en-IN', { maximumFractionDigits: 2 }), label: 'Quintals', detail: 'Available to Sell', icon: a.navMyFarm }, { value: String(data.summary.activeBatchCount), label: 'Active Batches', detail: 'Available Produce', icon: a.farm }].map((metric, i) => <View key={metric.label} style={[s.metric, i > 0 && s.separator]}><View style={s.metricTop}><Icon source={metric.icon} size={20} /><Text style={s.metricValue}>{metric.value}</Text></View><Text style={s.label}>{metric.label}</Text><Text style={s.meta}>{metric.detail}</Text></View>)}
      </Intent><Intent intent={{ type: 'AVAILABLE_PRODUCE' }} label="Available Produce" style={s.available}><Text style={s.linkText}>Available Produce</Text><Text style={s.linkText}>{data.summary.totalAvailableKg > 0 ? quintals(data.summary.totalAvailableKg) : 'None available'} ›</Text></Intent></View>
      <View style={s.card}><Heading title="My Crops" action={{ label: 'View All Crops', intent: { type: 'CROPS' } }} />
        {data.crops.length === 0 ? <View style={s.empty}><Icon source={a.farm} size={38} /><Text style={s.cropTitle}>No crops added yet.</Text><Text style={s.meta}>Add your first crop to keep{ '\n' }your farm information organized.</Text></View> : <View style={s.cropRow}>{data.crops.map(crop => <View key={crop.id} style={s.cropCard}>
          <Intent intent={{ type: 'CROP_DETAILS', cropId: crop.id, cropName: crop.name }} label={`${crop.name} crop details`} style={s.cropTop}><Image source={crop.image} resizeMode="cover" style={s.cropImage} /><View style={s.cropName}><Text style={s.cropTitle}>{crop.name}</Text><Text style={s.badge}>✓ {crop.status.charAt(0).toUpperCase() + crop.status.slice(1)}</Text></View></Intent>
          <View style={s.cropMetrics}><View style={s.cropMetric}><Text style={s.label}>{crop.availableKg > 0 ? quintals(crop.availableKg) : 'No produce'}</Text><Text style={s.meta}>Available</Text></View><Intent intent={{ type: 'BATCHES', cropId: crop.id, cropName: crop.name }} label={`${crop.name} physical batches`} style={s.cropMetric}><Text style={s.linkText}>{crop.batchCount} {crop.batchCount === 1 ? 'Batch' : 'Batches'}</Text><Text style={s.meta}>Active batches</Text></Intent></View>
          <Intent intent={{ type: 'CROP_DETAILS', cropId: crop.id, cropName: crop.name }} label={`View ${crop.name} Details`} style={s.outline}><Text style={s.linkText}>View Details →</Text></Intent>
        </View>)}</View>}
        {data.crops.length > 0 && data.summary.totalAvailableKg === 0 && <Text style={s.emptyCopy}>No available produce yet. Add produce to a crop when it is ready.</Text>}
        <Intent intent={{ type: 'ADD_CROP' }} label="Add Crop" style={s.add}><Icon source={a.plus} size={36} /><View style={s.flex}><Text style={s.cropTitle}>Add Crop</Text><Text style={s.meta}>Track more crops and manage your farm better.</Text></View><Text style={s.arrow}>›</Text></Intent>
      </View>
      <View style={s.card}><Heading title="Farm Activities" icon={a.listing} action={{ label: 'View All', intent: { type: 'UPDATES' } }} /><View style={s.cropRow}>
        {[{ value: data.activities.cropsAdded, label: 'Crops Added', action: 'View Crops', type: 'CROPS' as const, icon: a.farm, color: '#EFF8EB' }, { value: data.activities.updatesThisMonth, label: 'Updates This Month', action: 'View Updates', type: 'UPDATES' as const, icon: a.navMyFarm, color: '#FFF4E2' }].map(item => <Intent key={item.type} intent={{ type: item.type }} label={item.action} style={[s.activity, { backgroundColor: item.color }]}><View style={s.activityTop}><Icon source={item.icon} size={28} /><Text style={s.metricValue}>{item.value}</Text></View><Text style={s.meta}>{item.label}</Text><Text style={s.linkText}>{item.action} ›</Text></Intent>)}
      </View></View>
      <View style={s.card}><Heading title="Farm Location" action={{ label: 'View on Map', intent: { type: 'MAP' } }} /><View style={s.locationRow}><Intent intent={{ type: 'MAP' }} label="Farm map preview" style={s.map}><ImageBackground source={a.heroBackground} resizeMode="cover" style={s.mapArt}><Text style={s.pin}>⌖</Text><Text style={s.mapLabel}>Map preview coming soon</Text></ImageBackground></Intent><View style={s.locationDetails}><Text style={s.label}>{data.farm.location || 'Location not added'}</Text><Text style={s.meta}>{data.farm.area ?? '—'} Acres · Total Land Area</Text><Intent intent={{ type: 'MAP' }} label="View Full Map" style={s.outline}><Text style={s.linkText}>View Full Map →</Text></Intent></View></View></View>
    </View>
  </ScrollView><FarmerBottomNav onHome={onHome} /></View>;
}
const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#FAFAF2' }, scroll: { flex: 1 }, content: { paddingBottom: 12 }, flex: { flex: 1 }, state: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 28, gap: 18 }, stateTitle: { fontSize: 28, fontWeight: '800', color: '#064E31' }, stateMessage: { fontSize: 14, lineHeight: 20, color: '#53645D', textAlign: 'center' }, retry: { minWidth: 120, minHeight: 44, paddingHorizontal: 20, borderRadius: 10, backgroundColor: '#12642D', alignItems: 'center', justifyContent: 'center' }, retryText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },
  hero: { paddingHorizontal: 16, paddingBottom: 6 }, brandRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, logo: { width: 148, height: 44 }, bell: { minWidth: 44, minHeight: 44, borderRadius: 28, backgroundColor: '#FFFFFFE0', alignItems: 'center', justifyContent: 'center' },
  heroRow: { flexDirection: 'row', alignItems: 'flex-end', minHeight: 144, gap: 4 }, intro: { flex: 1.3, paddingBottom: 10, gap: 6 }, title: { fontSize: 29, fontWeight: '800', color: '#064E31' }, subtitle: { fontSize: 12, lineHeight: 17, color: '#223E3C' }, location: { marginTop: 10, backgroundColor: '#F4FAECED', borderRadius: 16, padding: 8, fontSize: 10, fontWeight: '600', color: '#203E36' }, farmer: { width: 112, height: 146 }, heroAside: { width: 76, gap: 8, paddingBottom: 8 }, callout: { padding: 7, borderRadius: 10, backgroundColor: '#FFFFF5ED', color: '#155A31', fontSize: 12, fontStyle: 'italic', textAlign: 'center' }, edit: { minHeight: 36, backgroundColor: '#F7FFF1', borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  body: { paddingHorizontal: 12, gap: 12 }, card: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 10, gap: 8, boxShadow: '0 3px 12px #536A3210' }, heading: { flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 32 }, headingText: { flex: 1, fontSize: 17, fontWeight: '800', color: '#183C37' }, link: { minHeight: 44, justifyContent: 'center' }, linkText: { fontSize: 11, fontWeight: '600', color: '#1A4937' }, overview: { flexDirection: 'row', backgroundColor: '#F5FAF2', paddingVertical: 8, borderRadius: 12 }, metric: { flex: 1, paddingHorizontal: 6, gap: 3, alignItems: 'flex-start' }, separator: { borderLeftWidth: 1, borderLeftColor: '#E0EBDE' }, metricTop: { flexDirection: 'row', alignItems: 'center', gap: 3 }, bellMask: { position: 'absolute', width: 9, height: 9, right: 9, top: 9, backgroundColor: '#FFFFFF', borderRadius: 5 }, metricValue: { fontSize: 18, fontWeight: '800', color: '#173F2D' }, label: { fontSize: 11, fontWeight: '700', color: '#243C32' }, meta: { fontSize: 10, lineHeight: 14, color: '#53645D' }, available: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 36, paddingHorizontal: 6 },
  cropRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' }, cropCard: { flex: 1, minWidth: 145, backgroundColor: '#FDFEFB', borderRadius: 12, padding: 5, gap: 9 }, cropTop: { flexDirection: 'row', alignItems: 'center', gap: 7, minHeight: 66 }, cropImage: { width: 66, height: 66, borderRadius: 8 }, cropName: { flex: 1, gap: 5 }, cropTitle: { fontSize: 15, fontWeight: '800', color: '#183C2D' }, badge: { fontSize: 10, color: '#267135', backgroundColor: '#DDF2D6', padding: 4, borderRadius: 12 }, cropMetrics: { flexDirection: 'row', gap: 6 }, cropMetric: { flex: 1, gap: 3, minHeight: 38, justifyContent: 'center' }, outline: { borderWidth: 1, borderColor: '#B7CDC3', borderRadius: 12, minHeight: 36, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 5 }, add: { flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderStyle: 'dashed', borderColor: '#C1E1B7', backgroundColor: '#F5FBF0', padding: 12, borderRadius: 12, minHeight: 62 }, arrow: { fontSize: 24, color: '#145736' },
  activity: { flex: 1, minWidth: 80, padding: 9, gap: 8, borderRadius: 12, minHeight: 92, justifyContent: 'space-between' }, activityTop: { flexDirection: 'row', alignItems: 'center', gap: 9 }, locationRow: { flexDirection: 'row', gap: 10 }, map: { flex: 1, borderRadius: 10, overflow: 'hidden' }, mapArt: { flex: 1, minHeight: 94, alignItems: 'center', justifyContent: 'center' }, pin: { fontSize: 34, color: '#C64D35' }, mapLabel: { fontSize: 9, padding: 4, backgroundColor: '#FFFFFFDC' }, locationDetails: { flex: 1, gap: 8, justifyContent: 'center' }, empty: { alignItems: 'center', padding: 18, gap: 8 }, emptyCopy: { padding: 10, fontSize: 12, color: '#53645D' },
});



