import type { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export function ScreenLayout({ children }: PropsWithChildren) {
  return <SafeAreaView style={styles.safe} edges={['top','bottom']}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.flex}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled">{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
export function BrandMark() { return <View style={styles.brand}><Text style={styles.brandLeaf}>⌁</Text><Text style={styles.brandText}>FarmPrism</Text></View>; }
export function ScreenIntro({title,description}:{title:string;description?:string}){return <View style={styles.intro}><Text style={styles.title}>{title}</Text>{description&&<Text style={styles.desc}>{description}</Text>}</View>}
export function PrimaryButton({label,onPress,disabled=false,loading=false}:{label:string;onPress:()=>void;disabled?:boolean;loading?:boolean}){return <Pressable onPress={onPress} disabled={disabled||loading} style={[styles.button,(disabled||loading)&&styles.disabled]}>{loading?<ActivityIndicator color="#fff"/>:<Text style={styles.buttonText}>{label}</Text>}</Pressable>}
export function SecondaryButton({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.secondary}><Text style={styles.secondaryText}>{label}</Text></Pressable>}
export function TextButton({label,onPress}:{label:string;onPress:()=>void}){return <Pressable onPress={onPress} style={styles.textButton}><Text style={styles.textButtonText}>{label}</Text></Pressable>}
export function Field({label,value,onChangeText,placeholder,keyboardType='default',autoCapitalize='sentences'}:{label:string;value:string;onChangeText:(v:string)=>void;placeholder:string;keyboardType?:'default'|'phone-pad'|'number-pad'|'email-address';autoCapitalize?:'none'|'sentences'}){return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} keyboardType={keyboardType} autoCapitalize={autoCapitalize} placeholderTextColor="#879088" style={styles.input}/></View>}
export function InlineMessage({children,tone='error'}:{children:ReactNode;tone?:'error'|'info'}){return <Text style={tone==='error'?styles.error:styles.info}>{children}</Text>}
export function Divider(){return <View style={styles.divider}/>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F8F2'},flex:{flex:1},scroll:{flexGrow:1,padding:24,justifyContent:'center'},brand:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:24},brandLeaf:{backgroundColor:'#DCEBD5',color:'#2F6F3B',borderRadius:24,paddingHorizontal:12,paddingVertical:7,fontSize:20},brandText:{fontSize:26,fontWeight:'800',color:'#24442D'},intro:{marginBottom:22},title:{fontSize:30,fontWeight:'800',color:'#24442D'},desc:{fontSize:16,color:'#53645A',marginTop:8,lineHeight:23},button:{height:54,borderRadius:9,backgroundColor:'#2F7A3E',alignItems:'center',justifyContent:'center'},buttonText:{color:'#fff',fontSize:17,fontWeight:'800'},secondary:{height:54,borderRadius:9,borderWidth:1,borderColor:'#CBD7C9',alignItems:'center',justifyContent:'center',paddingHorizontal:18},secondaryText:{color:'#24442D',fontWeight:'700',fontSize:16},textButton:{paddingVertical:10,alignItems:'center'},textButtonText:{color:'#2F7A3E',fontWeight:'700',fontSize:15},disabled:{opacity:.5},field:{gap:7},label:{color:'#24442D',fontWeight:'700',fontSize:14},input:{height:52,borderRadius:9,borderWidth:1,borderColor:'#C7D2C5',backgroundColor:'#fff',paddingHorizontal:14,color:'#21372A',fontSize:16},error:{color:'#A34238',fontSize:14,lineHeight:20},info:{color:'#53645A',fontSize:14,lineHeight:20},divider:{height:1,backgroundColor:'#D8E0D4',marginVertical:10}});
